In [1]:
#getting data from urls
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
#function for getting data and preparing DataFrame
def get_df(url):
    names = []
    rates = []
    styles = []
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')
    table = soup.find('table')
    rows = table.find_all('tr')
    for row in rows:
        if row == rows[0]:
            continue
        tds = row.find_all('td')
        names.append(str(tds[1].text))
        rates.append(str(tds[2].text))
        styles.append(str(tds[4].text))
    
    df = pd.DataFrame(list(zip(names, rates, styles)), columns = ['Name', 'Rate', 'Style'])
    df['Rate'] = df['Rate'].astype('float') #changed datatype for grouping
    return df

In [30]:
#DataFrames
df_de = get_df('https://www.ratebeer.com/beer/country/germany/79/')
by_style_de = df_de.groupby('Style').mean().sort_values('Rate', ascending=False)
df_pl = get_df('https://www.ratebeer.com/beer/country/poland/163/')
by_style_pl = df_pl.groupby('Style').mean().sort_values('Rate', ascending=False)
df_usa = get_df('https://www.ratebeer.com/beer/country/united-states/213/')
by_style_usa = df_usa.groupby('Style').mean().sort_values('Rate', ascending=False)

In [31]:
#data from Poland
df_pl.head(10)

,Name,Rate,Style
0,Szałpiw Buba Extreme Jack Daniels BA,4.24,Quadrupel / Abt
1,Artezan Samiec Alfa (Barrel Aged),4.18,Stout - Imperial
2,Kormoran Imperium Prunum,4.17,Porter - Baltic
3,Fortuna Komes Wymrażany Barley Wine Cognac BA,4.15,Bock - Eisbock
4,Szałpiw Buba Extreme Cognac BA,4.10,Quadrupel / Abt
5,Apis Półtorak Jadwiga,4.10,Mead - Melomel/Fruited
6,Widawa 5th Anniversary Imperial Baltic Porter ...,4.09,Porter - Baltic
7,Brokreacja Potion #2,4.06,Brown Ale - Imperial
8,PINTA Risfactor Double BA Bourbon & Rum,4.06,Stout - Imperial
9,Widawa 5th Anniversary Imperial Smoked Baltic ...,4.05,Porter - Baltic

In [32]:
by_style_pl

                                      Rate
Style
Bock - Eisbock                    4.085000
Quadrupel / Abt                   4.077500
Brown Ale - Imperial              4.035000
Sour / Wild Beer                  4.030000
Mead - Melomel/Fruited            4.030000
Porter - Baltic                   3.997143
Traditional Ale - Other           3.990000
Stout - Imperial Flavored         3.990000
Stout - Imperial                  3.982727
Sour/Wild - Dark                  3.960000
IIPA - Imperial Hazy / NEIPA      3.940000
BarleyWine / WheatWine / RyeWine  3.940000
Apple Cider-Ice/Fire/Fortified    3.933333
Sour - Flanders Red / Bruin       3.930000
Mead - Braggot/Hopped             3.920000
Porter - Smoked                   3.910000
Porter - Imperial                 3.910000

In [33]:
#data from Germany
df_de.head(10)

,Name,Rate,Style
0,Freigeist / h.ertie Eszett Geuze R,4.08,Lambic - Gueuze
1,Ayinger Celebrator Doppelbock,4.03,Bock - Doppelbock
2,Schneider Weisse Aventinus,3.99,Bock - Weizenbock
3,Freigeist / h.ertie Lambik Ohrwal R,3.95,Sour / Wild Beer
4,Seinsheimer Sasemer Danzbier Hell,3.94,Zwickelbier/Kellerbier/Landbier
5,Seinsheimer Dunkles Kellerbier,3.94,Dark Lager - Dunkel / Tmavý
6,Schönramer Barrel Aged Imperial Stout - Kentuc...,3.91,Stout - Imperial
7,Aecht Schlenkerla Fastenbier,3.89,Smoked - Rauchbier
8,Schneider Aventinus Weizen-Eisbock,3.89,Bock - Eisbock
9,Aecht Schlenkerla Rauchbier Urbock,3.87,Smoked - Rauchbier

In [34]:
by_style_de

                                      Rate
Style
Lambic - Gueuze                   4.080000
Dark Lager - Dunkel / Tmavý       3.940000
Sour / Wild Beer                  3.885000
Smoked - Rauchbier                3.867500
Zwickelbier/Kellerbier/Landbier   3.865000
Bock - Doppelbock                 3.860000
Bock - Eisbock                    3.845000
Weissbier - Hefeweizen            3.830000
Pale Lager - India / Hoppy        3.810000
Sour / Wild Beer - Flavored       3.810000
Bock - Weizenbock                 3.802000
Stout - Imperial                  3.783333
Wheat Ale - India / Hopfenweisse  3.765000
Stout - Extra / Foreign           3.760000
Traditional Ale - Other           3.760000
Altbier / Sticke Alt              3.760000
IIPA - Imperial Hazy / NEIPA      3.752000
IPA - Black/Brown/Cascadian Dark  3.740000
Porter - Imperial                 3.730000
IPA - Hazy / NEIPA                3.726667
Sour/Wild - Dark                  3.720000

In [35]:
#data from USA
df_usa.head(10)

,Name,Rate,Style
0,Toppling Goliath Kentucky Brunch,4.52,Stout - Imperial Flavored
1,B. Nektar Ken Schramm Signature Series - The H...,4.42,Mead - Melomel/Fruited
2,Schramm's The Heart of Darkness,4.42,Mead - Melomel/Fruited
3,Cigar City Pilot Series Dragonfruit Passion Fr...,4.42,Berliner Weisse - Flavored
4,Goose Island Bourbon County Stout - Rare 2010 ...,4.41,Stout - Imperial
5,Toppling Goliath Mornin' Delight,4.40,Stout - Imperial Flavored
6,Cigar City Hunahpu's Imperial Stout - Double B...,4.39,Stout - Imperial Flavored
7,Cycle / 3 Sons Rare Scooop R,4.38,Stout - Imperial Flavored
8,New Glarus R & D Sour Fruit - Wild Blackberry ...,4.36,Sour / Wild Beer - Flavored
9,Three Floyds Dark Lord - Bourbon Barrel Aged,4.36,Stout - Imperial Flavored

In [36]:
by_style_usa

                                      Rate
Style
Berliner Weisse - Flavored        4.370000
Sour / Wild Beer - Flavored       4.360000
Stout - Imperial Flavored         4.331875
Mead - Melomel/Fruited            4.329000
IIPA - Imperial / Double IPA      4.310000
Stout - Imperial                  4.295833
Saison / Farmhouse / Grisette     4.290000
BarleyWine / WheatWine / RyeWine  4.272500
Sour / Wild Beer                  4.260000